### ISSUE TITLE
Magic Feather Borked in pack ver 1.0.7

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/CreateTogether#11]
**Modpack version**
1.0.7
**Describe the bug**
magic feather is extremely glitchy, at least on a server, in pack ver 1.0.7... maybe some conflict with create stuff and additions? Seems to be more of an issue on the server, but is slightly present in my SP testing as well... I had others come test on the server as well so not just me xD

Edit: found a better way to test the bug in SP since it isnt nearly as noticeable... when you fly out of beacon range with the magical feather u fall down but slightly more controlled fall and you dont take fall damage... with create:stuff additions installed when you fly out of beacon range you fall straight down and take fall damage, disabling the mod puts it back to normal.

Sadly this mod doesnt seem to have a github repo, discord, curse issue tracker, curse comment section or even a config lol...

In one of our packs i would def suggest yeeting it alltogether(ofc you prolly wouldnt have put it in one of our packs especially missing any option for reporting an issue), but considering this is a curated pack, i might suggest yeeting the magic feather and just having one creative flight option being the jetpack? I guess that's all up to Senor Shwamy

**Screenshots**
https://gyazo.com/6363cc6a6e88b9d63ec9dcdfff8a942e

**Comment by theboo** [comment]
very similar to this issue:
https://github.com/Ephys/minecraft-magic-feather/issues/15

but the person never says which mod was the culprit lol

**Comment by NillerMedDild** [comment]
The dangers of adding MCCreator mods >_< I'll ask X which one he would prefer to keep.

**Comment by NillerMedDild** [comment]
What is the the glitch on servers exactly?

**Comment by theboo** [comment]
At least on our server you just can't get flying. You start flying for a split second then fall back down.. sometimes you can power through it but then even landing is weird lol

**Comment by Discomanco** [comment]
The jet-pack in general is weird.  

If you try to double tap to activate flight (like Creative Flight), it will instead stutter zoom while slowfalling, until you move (https://gyazo.com/ea1fdc2139112385ad9ef516172491f1).  
Even activating the Creative Flight can be tricky at times.  
If you stand on a block away from an edge, slowfall activates, draining durability (https://gyazo.com/64bdfa2e8e210aaa41348d8981fc4d16) - questionable design choice/limitation
No keybinds to toggle anything.  
Uses durability instead of something interesting fuel mechanic :(

**Comment by Discomanco** [comment]
Doing a bit of testing at Boos base, it seems that the Jetpack simply overrides the creative flight that the Magic Feather would give, with the same quirks.
At least actual Creative Flight is not altered

**Comment by theboo** [comment]
Yeah, i think they are fighting each other somehow cuz the jetpack doesnt behave like that in SP, it's more just creative flight with a slowfall effect that can be counteracted with sneak... How Disco's jetpack is running is exactly how the magic feather is running right now...

but the biggest downfall is that the cogs dont spin while flying!!!

**Comment by NillerMedDild** [comment]
Removing the mod again 👍 Thanks!
