### ISSUE TITLE
black stained glass

### ISSUE THREAD

**Issue by schouttetenspieter** [NillerMedDild/CreateTogether#13]
**Modpack version**
1.0.7 and 1.0.8
**Describe the bug**

when me or my friend tries to craft black stained glass the server crashes
when I spawn it in with /give no problem just the crafting itself is broken.  

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
https://pastebin.com/jnNpjF0k

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. It seems to be caused by FastSuite, I'll relay asap :)

**Comment by NillerMedDild** [comment]
I have removed the mod in v1.0.9, thanks again for the report.
