### ISSUE TITLE
[Suggestion] Add RandomPatches to help make multiplayer easier for low spec PCs

### ISSUE THREAD

**Issue by landretk** [NillerMedDild/CreateTogether#16]
Apologies for the bug label, there's no suggestion template for this pack.

**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/randompatches-forge

**Mod description**
Bug fixes and quality of life improvements for Minecraft, and additionally allows several hardcoded settings to be configured.

**Why would you like the mod added?**
Mainly for the option it gives to increase read timeouts and join timeouts. I'd like to run this pack on my server but I'm hesitant because I have several players that usually cannot join with the default read timeout of 30s without getting kicked. I have seen at least one player in the discord not able to join the official server for this reason too.

**Comment by NillerMedDild** [comment]
Ah yes, good idea.
