### ISSUE TITLE
CobbleGenRandomizer Integration not working

### ISSUE THREAD

**Issue by paper-soup** [NillerMedDild/CreateTogether#17]
1.16.5-1.0.9

Was trying to make an andesite generator using the CobbleGenRandomizer mod and none of the configuration is working. The built in crafting guide says to put a piece of andesite underneath the generator but it doesn't effect the generation, and the generator keeps generating random cobble and vanilla ores.

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.

**Screenshots**

**Comment by NillerMedDild** [comment]
Thanks for the report. Please provide screenshots of your setup :)

**Comment by paper-soup** [comment]
![2021-06-28_12 27 24](https://user-images.githubusercontent.com/86618168/123685795-4c862900-d80c-11eb-89a6-9942cfeb8802.png)

**Comment by NillerMedDild** [comment]
Hmm.. How did you download the modpack? It kinda sounds like you don't have the pack specific configs.

**Comment by paper-soup** [comment]
I installed it via Curseforge, the only extra mods added are Tinker's Construct and Biomes o' Plenty. The server im playing on is running on an external service so maybe the configs got lost in the shuffle

**Comment by NillerMedDild** [comment]
That might be it, could you check the `cobblegenrandomizer-common.toml` config please?

**Comment by paper-soup** [comment]
![image](https://user-images.githubusercontent.com/86618168/123686707-4e042100-d80d-11eb-87d6-c63c4a8a4045.png)

**Comment by paper-soup** [comment]
I went and did some testing in a singleplayer world and its working fine so it has something to do with the server I have running

**Comment by NillerMedDild** [comment]
I wanted you to check the config on the server :P but I guess we have our answer. 👍
