### ISSUE TITLE
Add Renewable Zinc/Copper Washing Recipes

### ISSUE THREAD

**Issue by yuri0r** [NillerMedDild/CreateTogether#24]
**1.1.0**

**Describe the bug**
not a bug. a suggestions. since 1.1.0 removed ex nihil and with it the only renewable source of zinc and copper. it would be great to re add the option for it the create way. 

i suggest by adding 

- zinc_nuggets to the red sand washing with a 5% chance 
- copper_nuggets to gravel wasching with a 5% chance 
to stay semi close in relation of gold/zinc iron/copper with the sieves. wich usualy was about 1/2 or 1/3 of the main source (gold/iron)

**Comment by NillerMedDild** [comment]
Thanks for the suggestion! I considered doing something like this, but thought I'd rather people get into Create mining machines to get their Zinc and Copper... However, more options within Create is good, so sure 😄

**Comment by yuri0r** [comment]
yeah there has been some discussion on discord. our server is bad and terrain kinda seen as precius. so we might hold off on the update than :)

**Comment by NillerMedDild** [comment]
The update with this change should be available this evening :)
