### ISSUE TITLE
Add Login Protection Mod

### ISSUE THREAD

**Issue by yuri0r** [NillerMedDild/CreateTogether#26]
**1.1.1**

These suggestions mainly aim at improving Server experience, given the pack is fairly lite it does attract players with lower hardware, thanks to randompatches these players dont time out as much anymore but end up staying in the world unable to do move for a fairly long time when first logging in and end up dying to hostile mobs [Login Protection](https://www.curseforge.com/minecraft/mc-mods/micles-login-protection) should solve this issiue

also the addition of [QuickHomes ](https://www.curseforge.com/minecraft/mc-mods/quickhomes) and [QuickTeleports](https://www.curseforge.com/minecraft/mc-mods/quickteleports) was met very positifly on my server. these mods ad /sethome /home and the usual /tpa commands and with that great convience.

**Comment by NillerMedDild** [comment]
Login Protection, absolutely, but I don't think convenience commands would fit in, I'd rather leave that up to server owners to add :)
