### ISSUE TITLE
Limestone to Copper nugget washing recipe conflicts with Create limestone to weathered limestone recipe

### ISSUE THREAD

**Issue by landretk** [NillerMedDild/CreateTogether#27]
**Modpack version**
1.1.1

**Describe the bug**
Create already has a recipe for washing Limestone and it seems to completely override the new recipe.

**Screenshots**
![2021-07-06_22 18 08](https://user-images.githubusercontent.com/4535529/124700156-75ac5680-dea9-11eb-96de-a50fffd75f59.png)
![2021-07-06_22 18 25](https://user-images.githubusercontent.com/4535529/124700162-780eb080-dea9-11eb-9a4a-865003954bba.png)

**Comment by NillerMedDild** [comment]
Oh, oops ^^'

**Comment by landretk** [comment]
Also that recipe is useful since I used it to get enough weathered limestone for my base, so I changed it to use limesand as an input instead, which has no real uses besides that it can be cooked into limestone.
