### ISSUE TITLE
Create Add-on mods [suggestion]

### ISSUE THREAD

**Issue by DamienTC** [NillerMedDild/CreateTogether#29]
https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions

https://www.curseforge.com/minecraft/mc-mods/createaddition

**Comment by NillerMedDild** [comment]
No thank you.

Create Stuff Additions we've already had, it causes some pretty hacky issues with flight.

Create Additions kinda.. adds too much.

Also, there's a reason there's only a bug template in this repo you know :)
