### ISSUE TITLE
[suggestion] simple storage network

### ISSUE THREAD

**Issue by DamienTC** [NillerMedDild/CreateTogether#30]
[suggestion] 
Simple Storage Network: https://www.curseforge.com/minecraft/mc-mods/simple-storage-network
(optional but highly recomended) Created storage network Resource Pack
https://www.curseforge.com/minecraft/texture-packs/created-storage-network/screenshots
![createstorage](https://user-images.githubusercontent.com/75565734/124816590-ebee9e80-df25-11eb-8089-dc9126c55c3d.png)

**Comment by theboo** [comment]
CreateTogether uses a heavily trimmed down Refined Storage that emulates simple storage networks but way less buggy
