### ISSUE TITLE
Copy-Paste Gadgets Not Working

### ISSUE THREAD

**Issue by kyernftw5** [NillerMedDild/CreateTogether#32]
Create Together v1.1.3

After copying the blocks I wanted, pasting it does not work. It only shows a green text showing 'Template build'. I have seen other users solving it by setting the MaxEnergyUsage and MaxEnergy to 0, but I'm not sure. (Link to it, https://github.com/Direwolf20-MC/BuildingGadgets/issues/486).

Edit: Does work in Creative mode though.

![2021-07-18_19 04 49](https://user-images.githubusercontent.com/21281113/126064801-92e5a88c-9d08-485d-be1d-3e6ba32dfd9a.png)

**Comment by NillerMedDild** [comment]
The configs are already set to that. Did you have the required materials to make the build? :)

**Comment by kyernftw5** [comment]
Yes, I do. Seems weird why this would happen though.

**Comment by NillerMedDild** [comment]
Yeah :/ I'll look into it.

**Comment by NillerMedDild** [comment]
There was something wrong with the config format or.. something. Fixed in-dev 👍
