### ISSUE TITLE
A few mods are not configurated properly for the modpack

### ISSUE THREAD

**Issue by Bobcatadam** [NillerMedDild/CreateTogether#34]
1.1.3

I know what is wrong, but not how to fix it. The cobble gens were not working properly, so the owner of the server had to go into the config files and add the custom recipes. We just found out that refined storage isn't correct either, and is still using the normal crafting and functionality. My hunch is that the mods are all functioning on default configs server side, because my client is still 100% as it should be. How are you supposed to put the mods on the server so that they don't lose the custom configs?

**Comment by theboo** [comment]
Stop the server. Delete your config, default config, and kubejs folders, also delete the serverconfigs folder in the world folder.

Grab the config, default config and kubejs folders from your client, put them on the server and start.

Don't worry about replacing the serverconfigs in world folder, those are pulled from default configs
