### ISSUE TITLE
Opening the FTB Chunks map crashes the game

### ISSUE THREAD

**Issue by chlorofomduck** [NillerMedDild/CreateTogether#36]
**Modpack version**
1.1.4
**Describe the bug**
When trying to open the FTB Chunks map, the game crashes with a "java.lang.reflect.UndeclaredThrowableException: null"

**Logs**
[crash-2021-07-30_14.43.20-client.txt](https://github.com/NillerMedDild/CreateTogether/files/6909482/crash-2021-07-30_14.43.20-client.txt)

**Screenshots**
NA

**Comment by NillerMedDild** [comment]
Thanks for the report. Please update to 1.1.5 and see if the issue persists.

**Comment by chlorofomduck** [comment]
Hi, I updated to 1.1.5 and the same thing happens.
[crash-2021-07-30_15.01.39-client.txt](https://github.com/NillerMedDild/CreateTogether/files/6909532/crash-2021-07-30_15.01.39-client.txt)

**Comment by NillerMedDild** [comment]
Alright, thanks for updating! 
Which dimension are you in when it crashes?
How are you trying to open the map? From the inventory/from hotkey?

**Comment by chlorofomduck** [comment]
I'm in the overworld, and I confirmed that it crashes with both the inventory button and the hotkey.

**Comment by NillerMedDild** [comment]
I cannot reproduce this :/ Perhaps try a reinstall?

**Comment by chlorofomduck** [comment]
Oh, I forgot to follow up here, sorry. I restarted the server and it started working again.
