### ISSUE TITLE
Building Gadget Mod Broken

### ISSUE THREAD

**Issue by kirjorjos** [NillerMedDild/CreateTogether#38]
**Modpack version**
1.1.6 (although it dates quite a few versions, I just haven't had time to submit the issue until now, still tested and broken in 1.1.6)
**Describe the bug**
When attempting to use any gadget made after RF was removed from pack, it shows a red hologram of the block it's set to rather than the proper colored one it should, which normally means it's out of power.  Attempting to use the gadget does nothing.
**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
N/A
**Screenshots**
![image](https://user-images.githubusercontent.com/35607697/134337503-7002740d-ab94-4b52-b242-ac72e171b0bb.png)
![image](https://user-images.githubusercontent.com/35607697/134337552-322192f9-b19d-4c84-b1ca-5d50aac491a8.png)

**Comment by NillerMedDild** [comment]
Thanks for the report. 
It sounds like your defaultconfigs folder is missing, meaning your serverconfigs were not correctly applied. Delete the serverconfigs folder from your world and replace your defaultconfigs folder with one from a fresh install of the pack :)

**Comment by kirjorjos** [comment]
Asking in the support channel really got me nowhere, and in terms of the default config folder being missing, well I would hope it isn't on the official server.  I've also had other players verify it isn't working for them.  Reinstalling the pack to reset the client configs also didn't help at all.

**Comment by NillerMedDild** [comment]
Ah sorry, I just slapped the support tag on because I verified that the gadgets work in 1.1.5 so I was certain it worked. I'll have another look asap.

**Comment by NillerMedDild** [comment]
The serverconfig was indeed broken on the official server.
