### ISSUE TITLE
updated server and have conflicts

### ISSUE THREAD

**Issue by DrMinelab** [NillerMedDild/CreateTogether#39]
### Modpack Version

1.7

### Describe your issue.

I have a Createtogether server on bisecthosting there was a update and i updated.  I am using the curse forge launcher and cant find the update to version 1.7 of the modpack.  I see a bunch of new mods, on the server mods list. where do i go, or what do i do to get to update. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
There is no CreateTogether version 1.7... 1.1.6 is the latest release :)
https://github.com/NillerMedDild/CreateTogether/blob/master/changelogs/changelog.md

**Comment by DrMinelab** [comment]
So it is on the bisecthosting side? I kind of figured i didint think that for a light mod pack would get the tons of mods that are there now

**Comment by NillerMedDild** [comment]
I reached out to them and it has been removed, thanks :)
You're very welcome to reach out to their support if you need any help with getting the server back to normal.
