### ISSUE TITLE
Potential missing step in multimc setup in readme? (or an extra unneeded step)

### ISSUE THREAD

**Issue by deadcyclo** [NillerMedDild/CreateTogether#4]
It seems odd to me that you have a step for 'git pull origin develop' without a 'git checkout develop'. I mean, if you want people to run from the master branch, the pull isn't needed, and if you want people to run from the develope branch, they need to check out?

**Comment by NillerMedDild** [comment]
Ah you're right about that, thanks for the correction 👍
