### ISSUE TITLE
Crash after world generation (on linux)

### ISSUE THREAD

**Issue by deadcyclo** [NillerMedDild/CreateTogether#5]
**Modpack version**
both develop branch and master branch

**Describe the bug**
I'm getting an array index out of bounds exception crash at the end of world generation (on Linux). I've tested both master and develop branches, and both the latest (36.1.16) and the latest recommended (36.1.0) version of forge.

**Logs**
https://pastebin.com/JXRNQiHr

**Comment by NillerMedDild** [comment]
Please remove the mod BiomeIdFixer, that should allow you to start up :)

**Comment by NillerMedDild** [comment]
It seems to be this issue: https://github.com/desagas/Biome-Id-Fixer/issues/4

**Comment by deadcyclo** [comment]
I can confirm deactivating the mod did the trick (not that anything else was expected). Seems that it probably should be safe to remove the mod completely. As far as I can tell, the mod isn't needed for worlds generated with forge version 36.0.2 or later, and since the modpack is new, I would think that that wouldn't ever happen.

**Comment by deadcyclo** [comment]
Oh. I see that information was available in the bug report you linked. Well. I guess I summarized it for you :D

**Comment by desagas** [comment]
I apologize that I did not see this sooner. I am working on it actively right now. Fingers crossed I can fix it soon!
