### ISSUE TITLE
Mesh Duplication

### ISSUE THREAD

**Issue by Sufilevy** [NillerMedDild/CreateTogether#6]
Whenever you put a mesh in a sieve and then Carry On that sieve (Shift + Right Click from 2ish block radius), the sieve goes into your hand, the mesh goes into your inventory, and when you put the sieve back down it doesn't show that it has a mesh (probably a visual glitch) but you can still Shift + Right Click from further away to take the mesh out, or you can keep Carry On that sieve and thus duplicating the mesh.

**Comment by NillerMedDild** [comment]
Carry On isn't in this modpack, did you add it yourself? :P
