### ISSUE TITLE
Graphical Glitches in Survival World

### ISSUE THREAD

**Issue by h20helps** [NillerMedDild/CreateTogether#8]
**Modpack version**
1.0.6

**Describe the bug**
The bug happens when I start to move my cursor and my character, the screen starts to glitch out with lines, weird text, or just complete darkness covering the screen.

**Logs**
This is my latest in the Logs folder
https://gist.github.com/h20helps/8193a0a212625e15782b0f46fc7d9326#file-latest-txt

**Screenshots**
![2021-05-26_08 04 58](https://user-images.githubusercontent.com/84853205/119665953-8376b280-bdfa-11eb-89bc-bc43c930b8b3.png)21-05-26_08 03 59](https://user-images.githubusercontent.com/84853205/119665942-81acef00-bdfa-11eb-9d4e-e38bdd754ca0.png)![2021-05-26_08 04 58](https://user-images.githubusercontent.com/84853205/119665953-8376b280-bdfa-11eb-89bc-bc43c930b8b3.png)21-05-26_08 04 08](https://user-images.githubusercontent.com/84853205/119665947-82458580-bdfa-11eb-9b6c-0f44af181018.png)
![2021-05-26_08 04 39](https://user-images.githubusercontent.com/84853205/119665949-82de1c00-bdfa-11eb-83f5-5b4c65865a09.png)
![2021-05-26_08 04 55](https://user-images.githubusercontent.com/84853205/119665951-8376b280-bdfa-11eb-9564-04e03450be52.png)

**Comment by theboo** [comment]
Are you using optifine by chance?

**Comment by h20helps** [comment]
> Are you using optifine by chance?
I don't think so, This is the list of mods in this modpack
Architectury API (Forge)
shedaniel
architectury-1.15.13-forge.jar
Clumps
Jaredlll08
Clumps-6.0.0.22.jar
FastSuite
Shadows_of_Fire
FastSuite-1.16.4-1.0.1.jar
KubeJS (Forge)
LatvianModder
kubejs-1605.3.8-build.198-forge.jar
Rhino
LatvianModder
rhino-1.7.13-build.24.jar
The One Probe
McJty
theoneprobe-1.16-3.1.3.jar
AutoRegLib
Vazkii
AutoRegLib-1.6-47.jar
Better Advancements
way2muchnoise
BetterAdvancements-1.16.5-0.1.0.108.jar
Building Gadgets
Direwolf20
buildinggadgets-1.16.5-3.8.0.jar
Chocolate Fix
AlcatrazEscapee
chocolate-1.3.0-1.16.4.jar
Chunk-Pregenerator
Speiger
Chunk Pregenerator-V1.16-3.0.5.jar
Cloth Config API (Forge)
shedaniel
cloth-config-4.11.26-forge.jar
CobbleGenRandomizer
HorribleNerd
cobblegenrandomizer-1.16-5.1.2.jar
Colds: Easy Paxel (Lite) (FORGE)
Coldspell_Games
EasyPaxelLITE(Forge1.16.4)vrs1.0.3.jar
Construction Wand
ThetaDev
constructionwand-1.16.5-2.2.jar
CookieCore
Ephys
cookiecore-1.16.2-3.0.2-9389769.jar
Create
simibubi
create-mc1.16.5_v0.3.1c.jar
Decorative Blocks
stohun
decorative_blocks-1.16.4-1.7.2.jar
Drawers Tooltip
Snownee_
DrawersTooltip-1.16.2-2.1.0.jar
Dynamic View
someaddon
dynviewdist-1.9.jar
Ex Nihilo: Sequentia
NovaMachina
exnihilosequentia-1.16-2.0.2.6.jar
FastFurnace
Shadows_of_Fire
FastFurnace-1.16.4-4.4.0.jar
FastWorkbench
Shadows_of_Fire
FastWorkbench-1.16.4-4.5.1.jar
FerriteCore (Forge)
malte0811
ferritecore-2.0.4-forge.jar
FTB Ultimine (Forge)
FTB
ftb-ultimine-1605.2.0-build.26-forge.jar
Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.0.99.jar
KubeJS Create
LatvianModder
kubejs-create-1604.1.0.4.jar
Lazy DataFixerUpper(LazyDFU) [FORGE]
Corgi_Taco
lazydfu-0.1.3.jar
Magic Feather
Ephys
magicfeather-1.16.2-3.2.0.jar
More Overlays Updated
RiDGo8
moreoverlays-1.18.13-mc1.16.5.jar
PackMenu
Shadows_of_Fire
PackMenu-1.16.4-2.4.2.jar
Placebo
Shadows_of_Fire
Placebo-1.16.4-4.4.5.jar
Quark
Vazkii
Quark-r2.4-311.jar
Refined Storage
raoulvdberge
refinedstorage-1.9.12.jar
ServerConfig Updater
Darkere
serverconfigupdater-1.3.jar
Simple Magnets
SuperMartijn642
simplemagnets-1.1.2-mc1.16.5.jar
Simply Backpacks
Flanks255
simplybackpacks-1.16.3-1.4.13.jar
Storage Drawers
Texelsaur
StorageDrawers-1.16.3-8.2.2.jar
SuperMartijn642's Config Lib
SuperMartijn642
supermartijn642configlib-1.0.6-mc1.16.jar
SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.0.3-mc1.16.5.jar

**Comment by h20helps** [comment]
I figured out what the problem was. I had a windmill bearing that was WAY too big. In this mod pack, you only need a windmill at 31 (30 if you don't count the block height touching the bearing,) sails high on all four sides to reach max stress. When I read on the wiki I thought it said 128 high. Turns out once you get windmills around 60 high you start getting graphical glitches when they spin. However, when I tested windmills at the minimum you need to get the highest stress I had 20 of them running in one world without any graphical errors at all.
